name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            gradle: ./gradlew
          - os: windows-latest
            gradle: .\gradlew.bat
          - os: macos-latest
            gradle: ./gradlew

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-java@v4.3.0
        with:
          distribution: temurin
          java-version: 21

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - run: chmod +x gradlew
        if: runner.os != 'Windows'

      - run: ${{ matrix.gradle }} build

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-java@v4.3.0
        with:
          distribution: temurin
          java-version: 21

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ubuntu-gradle-web-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ubuntu-gradle-web-

      - run: chmod +x gradlew

      - run: ./gradlew :teavm:gdx_teavm_web_js_build
